apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ingress-test-namespace
  namespace: test-namespace
spec:
  hosts:
  - "*"
  gateways:
  - ingress-test-namespace
  http:
    - match:
        - uri:
            prefix: "/ya"
      route:
        - destination:
            host: test-nginx-proxy
            port:
              number: 8080
            subset: v2
          weight: 100
    - route:
        - destination:
            host: test-nginx-proxy
            port:
              number: 8080
            subset: v1
          weigth: 99
        - destination:
            host: test-nginx-proxy
            port:
              number: 8080
            subset: v2
          weigth: 1
