apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: namespace-test-namespace
  namespace: test-namespace
spec:
  selector:
    istio: namespace-test-namespace
  servers:
  - port:
      number: 8001
      name: http
      protocol: HTTP
    hosts:
    - "*"
